Repository phuoctmse/smoking-cessation-support-platform, pull requests merged in 2025-07, with the labels that each got.

#74 fix(user): fix create user in role admin
  src/routes/auth/auth.repository.ts
  src/routes/auth/schema/signup.schema.ts
  src/routes/user/dto/create-user.input.ts
  src/routes/user/entities/user.entity.ts
  src/routes/user/schema/user.schema.ts
  src/routes/user/user.module.ts
  src/routes/user/user.repo.ts
  src/routes/user/user.resolver.ts
  src/routes/user/user.service.ts
  src/shared/enums/graphql-enums.ts
Labels: Possible security concern, Review effort 4/5

#81 Feature/chat
  package-lock.json
  package.json
  prisma/migrations/20250703133440_rename_subscription_to_user_subscription/migration.sql
  prisma/migrations/20250703133545_remove_session_id_unique_constraint/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/routes/cessation-plan/cessation-plan.repository.ts
  src/routes/chat/chat.module.ts
  src/routes/chat/chat.repository.ts
  src/routes/chat/chat.resolver.ts
  src/routes/chat/dto/create-chat-message.input.ts
  src/routes/chat/dto/create-chat-room.input.ts
  src/routes/chat/dto/request/create-chat-message.input.ts
  src/routes/chat/dto/request/create-chat-room.input.ts
  src/routes/chat/entities/chat-message.entity.ts
  src/routes/chat/entities/chat-room.entity.ts
  src/routes/subscription/entities/subscription.entity.ts
  src/routes/subscription/subscription.cron.ts
  src/routes/subscription/subscription.repo.ts
  src/routes/subscription/subscription.resolver.ts
  src/routes/transaction/transaction.repo.ts
  src/shared/config/websocket.config.ts
  src/shared/guards/jwt-auth.guard.ts
  src/shared/guards/subscription.guard.ts
  src/shared/modules/supabase.module.ts
  src/shared/shared.module.ts
Labels: Possible security concern, Review effort 4/5

#87 Cooking mode
  package-lock.json
  src/app.module.ts
  src/routes/cessation-plan-template/cessation-plan-template.module.ts
  src/routes/cessation-plan-template/cessation-plan-template.repository.ts
  src/routes/cessation-plan-template/cessation-plan-template.service.ts
  src/routes/cessation-plan-template/schema/update-cessation-plan-template.schema.ts
  src/routes/cessation-plan/cessation-plan.cron.ts
  src/routes/cessation-plan/cessation-plan.module.ts
  src/routes/cessation-plan/cessation-plan.repository.ts
  src/routes/cessation-plan/cessation-plan.service.ts
  src/routes/plan-stage-template/plan-stage-template.module.ts
  src/routes/plan-stage-template/plan-stage-template.repository.ts
  src/routes/plan-stage-template/plan-stage-template.service.ts
  src/routes/plan-stage/plan-stage.cron.ts
  src/routes/plan-stage/plan-stage.module.ts
  src/routes/plan-stage/plan-stage.repository.ts
  src/routes/plan-stage/plan-stage.service.ts
Labels: bug, enhancement

#88 perf(progress-record): add Redis caching to progress record service
  src/routes/progress-record/progress-record.module.ts
  src/routes/progress-record/progress-record.resolver.ts
  src/routes/progress-record/progress-record.service.ts
Labels: enhancement

#90 feat(health-score-criteria): implement HealthScoreCriteria module
  src/app.module.ts
  src/routes/health-score-criteria/dto/request/create-health-score-criteria.input.ts
  src/routes/health-score-criteria/dto/request/health-score-criteria-filters.input.ts
  src/routes/health-score-criteria/dto/request/update-health-score-criteria.input.ts
  src/routes/health-score-criteria/dto/response/paginated-health-score-criteria.response.ts
  src/routes/health-score-criteria/entities/health-score-criteria.entity.ts
  src/routes/health-score-criteria/health-score-criteria.module.ts
  src/routes/health-score-criteria/health-score-criteria.repository.ts
  src/routes/health-score-criteria/health-score-criteria.resolver.spec.ts
  src/routes/health-score-criteria/health-score-criteria.resolver.ts
  src/routes/health-score-criteria/health-score-criteria.service.spec.ts
  src/routes/health-score-criteria/health-score-criteria.service.ts
Labels: enhancement

#91 prisma(notification): add notification models
  prisma/migrations/20250712073436_add_notification_system/migration.sql
  prisma/schema.prisma
Labels: enhancement

#93 fix(progress-record): enhance cache invalidation
  src/routes/progress-record/progress-record.repository.ts
  src/routes/progress-record/progress-record.service.ts
Labels: bug, enhancement

#94 Feature/notification
  prisma/schema.prisma
  src/app.module.ts
  src/routes/badge-award/badge-award.module.ts
  src/routes/badge-award/badge-award.service.ts
  src/routes/cessation-plan/cessation-plan.module.ts
  src/routes/cessation-plan/cessation-plan.service.ts
  src/routes/notification-template/dto/request/create-notification-template.input.ts
  src/routes/notification-template/dto/request/notification-template-filters.input.ts
  src/routes/notification-template/dto/request/update-notification-template.input.ts
  src/routes/notification-template/dto/response/paginated-notification-templates.response.ts
  src/routes/notification-template/entities/notification-template.entity.ts
  src/routes/notification-template/notification-template.module.ts
  src/routes/notification-template/notification-template.repository.ts
  src/routes/notification-template/notification-template.resolver.spec.ts
  src/routes/notification-template/notification-template.resolver.ts
  src/routes/notification-template/notification-template.service.spec.ts
  src/routes/notification-template/notification-template.service.ts
  src/routes/notification/dto/request/notification-filters.input.ts
  src/routes/notification/dto/response/paginated-notifications.response.ts
  src/routes/notification/entities/notification.entity.ts
  src/routes/notification/notification.cron.ts
  src/routes/notification/notification.event.ts
  src/routes/notification/notification.module.ts
  src/routes/notification/notification.repository.ts
  src/routes/notification/notification.resolver.spec.ts
  src/routes/notification/notification.resolver.ts
  src/routes/notification/notification.service.spec.ts
  src/routes/notification/notification.service.ts
  src/routes/plan-stage/plan-stage.module.ts
  src/routes/plan-stage/plan-stage.service.ts
  src/shared/enums/graphql-enums.ts
Labels: enhancement

#97 Feature/recommend
  package-lock.json
  package.json
  prisma/migrations/20250712083308_refactor_field_for_recommend/migration.sql
  prisma/schema.prisma
  src/ai/recommendation/model.ts
  src/app.module.ts
  src/routes/auth/auth.repository.ts
  src/routes/cessation-plan/cessation-plan.module.ts
  src/routes/cessation-plan/cessation-plan.resolver.ts
  src/routes/cessation-plan/schema/ai-recommendation.schema.ts
  src/routes/profile-quiz/dto/request/create-profile-quiz.input.ts
  src/routes/profile-quiz/dto/request/update-profile-quiz.input.ts
  src/routes/profile-quiz/dto/response/profile-quiz-response.dto.ts
  src/routes/profile-quiz/entities/profile-quiz.entity.ts
  src/routes/profile-quiz/profile-quiz.module.ts
  src/routes/profile-quiz/profile-quiz.repository.ts
  src/routes/profile-quiz/profile-quiz.resolver.ts
  src/routes/profile-quiz/profile-quiz.service.ts
  src/routes/profile-quiz/schema/profile-quiz.schema.ts
  src/routes/quiz-attempt/quiz-attempt.entity.ts
  src/routes/quiz-attempt/quiz-attempt.schema.ts
  src/routes/quiz-question/dto/request/create-quiz-question.input.ts
  src/routes/quiz-question/dto/request/update-quiz-question.input.ts
  src/routes/quiz-question/dto/response/quiz-question-response.dto.ts
  src/routes/quiz-question/entities/quiz-question.entity.ts
  src/routes/quiz-question/quiz-question.module.ts
  src/routes/quiz-question/quiz-question.repository.ts
  src/routes/quiz-question/quiz-question.resolver.ts
  src/routes/quiz-question/quiz-question.service.ts
  src/routes/quiz-question/schema/quiz-question.schema.ts
  src/routes/quiz-response/dto/request/create-quiz-response.input.ts
  src/routes/quiz-response/dto/request/start-quiz.input.ts
  src/routes/quiz-response/dto/request/submit-quiz.input.ts
  src/routes/quiz-response/dto/response/quiz-response.object.ts
  src/routes/quiz-response/dto/response/submit-quiz.response.ts
  src/routes/quiz-response/entities/quiz-response.entity.ts
  src/routes/quiz-response/quiz-reponse.module.ts
  src/routes/quiz-response/quiz-response.repository.ts
  src/routes/quiz-response/quiz-response.resolver.ts
  src/routes/quiz-response/quiz-response.service.ts
  src/routes/quiz-response/schema/quiz-response.schema.ts
  src/routes/subscription/subscription.repo.ts
  src/routes/subscription/subscription.resolver.ts
  src/routes/subscription/subscription.service.ts
  src/routes/user/dto/create-user.input.ts
  src/routes/user/dto/update-user.input.ts
  src/routes/user/entities/member-profile.entity.ts
  src/routes/user/schema/user.schema.ts
  src/routes/user/user.resolver.ts
  src/shared/config/config.ts
  src/shared/constants/question-type.constant.ts
  src/shared/decorators/current-user.decorator.ts
  src/shared/services/custom-ai-recommendation.service.ts
  src/shared/services/quiz-to-profile-ai.service.ts
Labels: Possible security concern, Review effort 4/5

#98 hotfix RoleRole
  src/routes/profile-quiz/profile-quiz.resolver.ts
Labels: Review effort 1/5

#101 Fix/create cessation plan
  src/routes/cessation-plan-template/cessation-plan-template.repository.ts
  src/routes/cessation-plan-template/cessation-plan-template.service.ts
  src/routes/cessation-plan/cessation-plan.repository.ts
  src/routes/cessation-plan/cessation-plan.resolver.ts
  src/routes/cessation-plan/cessation-plan.service.ts
  src/routes/plan-stage/plan-stage.resolver.ts
  src/routes/plan-stage/plan-stage.service.ts
Labels: enhancement

#102 Feature/user
  eslint.config.mjs
  src/routes/auth/auth.repository.ts
  src/routes/auth/auth.service.ts
  src/routes/cessation-plan/cessation-plan.module.ts
  src/routes/cessation-plan/cessation-plan.service.ts
  src/routes/feedback/feedback.module.ts
  src/routes/feedback/feedback.service.ts
  src/routes/user/user.module.ts
  src/routes/user/user.repo.ts
  src/routes/user/user.resolver.ts
  src/routes/user/user.service.ts
Labels: Review effort 4/5

#103 Feature/recommend
  prisma/migrations/20250718084652_update_field_quiz_response/migration.sql
  prisma/schema.prisma
  src/routes/quiz-question/quiz-question.repository.ts
  src/routes/quiz-response/dto/request/create-quiz-response.input.ts
  src/routes/quiz-response/entities/quiz-response.entity.ts
  src/routes/quiz-response/quiz-response.repository.ts
  src/routes/quiz-response/quiz-response.resolver.ts
  src/routes/quiz-response/quiz-response.service.ts
  src/routes/user/user.module.ts
  src/routes/user/user.resolver.ts
Labels: Review effort 4/5

#104 Fix/change plan status
  src/routes/badge-award/badge-award.service.ts
  src/routes/plan-stage/plan-stage.cron.ts
  src/routes/plan-stage/plan-stage.module.ts
  src/routes/plan-stage/plan-stage.service.ts
Labels: enhancement

#107 Fix/change plan status
  package-lock.json
  src/routes/cessation-plan/cessation-plan.cron.ts
  src/routes/cessation-plan/cessation-plan.repository.ts
  src/routes/cessation-plan/cessation-plan.service.ts
  src/routes/notification/notification.event.ts
  src/routes/plan-stage/plan-stage.cron.ts
Labels: enhancement

#111 refactor: restore production cron schedule for plan stage
  src/routes/plan-stage/plan-stage.cron.ts
Labels: enhancement

#112 Develop
  src/routes/plan-stage/plan-stage.cron.ts
Labels: enhancement

#113 Feature/recommend
  README.md
  package-lock.json
  package.json
  src/app.module.ts
  src/instrument.ts
  src/main.ts
  src/routes/cessation-plan-template/cessation-plan-template.resolver.ts
  src/routes/cessation-plan-template/cessation-plan-template.service.ts
  src/shared/controllers/health.controller.ts
  src/shared/modules/elasticsearch.module.ts
  src/shared/services/cronjob-management.service.ts
  src/shared/services/cronjob.service.ts
  src/shared/services/data-sync.service.ts
  src/shared/services/elasticsearch.service.ts
  src/shared/services/sentry.service.ts
  src/shared/shared.module.ts
Labels: Possible security concern, Review effort 4/5

#117 Feature/recommend
  prisma/migrations/20250720150546_add_field_membership_package/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/routes/cessation-plan-template/cessation-plan-template.module.ts
  src/routes/cessation-plan/cessation-plan.module.ts
  src/routes/dashboard/dashboard.module.ts
  src/routes/dashboard/dashboard.repo.ts
  src/routes/dashboard/dashboard.resolver.ts
  src/routes/dashboard/dashboard.service.ts
  src/routes/dashboard/entities/dashboard.entity.ts
  src/routes/dashboard/entities/payment.entity.ts
  src/routes/health-score-criteria/health-score-criteria.module.ts
  src/routes/leaderboard/leaderboard.module.ts
  src/routes/membership-package/entities/membership.entity.ts
  src/routes/membership-package/membership.resolver.ts
  src/routes/membership-package/schema/membership.schema.ts
  src/routes/notification-template/notification-template.module.ts
  src/routes/notification/notification.module.ts
  src/routes/plan-stage/plan-stage.module.ts
  src/routes/progress-record/progress-record.module.ts
  src/shared/services/redis.service.ts
Labels: Review effort 4/5

#118 Develop
  prisma/migrations/20250720150546_add_field_membership_package/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/routes/cessation-plan-template/cessation-plan-template.module.ts
  src/routes/cessation-plan/cessation-plan.module.ts
  src/routes/dashboard/dashboard.module.ts
  src/routes/dashboard/dashboard.repo.ts
  src/routes/dashboard/dashboard.resolver.ts
  src/routes/dashboard/dashboard.service.ts
  src/routes/dashboard/entities/dashboard.entity.ts
  src/routes/dashboard/entities/payment.entity.ts
  src/routes/health-score-criteria/health-score-criteria.module.ts
  src/routes/leaderboard/leaderboard.module.ts
  src/routes/membership-package/entities/membership.entity.ts
  src/routes/membership-package/membership.resolver.ts
  src/routes/membership-package/schema/membership.schema.ts
  src/routes/notification-template/notification-template.module.ts
  src/routes/notification/notification.module.ts
  src/routes/plan-stage/plan-stage.module.ts
  src/routes/progress-record/progress-record.module.ts
  src/shared/services/redis.service.ts
Labels: Review effort 4/5

#120 Enhance/cessation plan template
  src/routes/cessation-plan-template/cessation-plan-template.repository.ts
  src/routes/cessation-plan-template/cessation-plan-template.service.ts
  src/routes/cessation-plan/cessation-plan.service.ts
  src/routes/plan-stage-template/dto/requests/create-plan-stage-template.input.ts
  src/routes/plan-stage-template/dto/requests/update-plan-stage-template.input.ts
  src/routes/plan-stage-template/entities/plan-stage-template.entity.ts
  src/routes/plan-stage-template/plan-stage-template.repository.ts
  src/routes/plan-stage-template/schema/create-plan-stage-template.schema.ts
  src/routes/plan-stage/dto/request/create-plan-stage.input.ts
  src/routes/plan-stage/dto/request/update-plan-stage.input.ts
  src/routes/plan-stage/entities/plan-stage.entity.ts
  src/routes/plan-stage/plan-stage.repository.ts
  src/routes/plan-stage/plan-stage.service.ts
  src/routes/plan-stage/schema/create-plan-stage.schema.ts
  src/routes/plan-stage/schema/update-plan-stage.schema.ts
Labels: enhancement

#122 feat(plan-stage): add plan stage chart
  src/routes/plan-stage/dto/request/plan-stage-chart-filters.input.ts
  src/routes/plan-stage/dto/response/plan-stage-chart.response.ts
  src/routes/plan-stage/plan-stage.repository.ts
  src/routes/plan-stage/plan-stage.resolver.ts
  src/routes/plan-stage/plan-stage.service.ts
  src/routes/progress-record/progress-record.service.ts
Labels: enhancement

#123 fix(leaderboard): refactor leaderboard logic
  src/routes/leaderboard/leaderboard.resolver.ts
  src/routes/leaderboard/leaderboard.service.ts
  src/routes/progress-record/progress-record.service.ts
Labels: enhancement

#128 fill missing field in schema
  src/routes/user/entities/member-profile.entity.ts
  src/routes/user/schema/user.schema.ts
Labels: Review effort 1/5

#129 Develop
  src/routes/user/entities/member-profile.entity.ts
  src/routes/user/schema/user.schema.ts
Labels: bug
